#!/bin/bash

if [ $# -eq 2 ]
then
	interface=$2
        interfacemon="${interface}mon"


	ifconfig $interface down
	dhclient -r $interface &> /dev/null # release ip

	if [ "$1" = "reset" ]; then
		echo 'Resetting MAC address...'
		echo
		macchanger -p $interface

	elif [ "$1" = "random" ]; then
		echo 'Randomising MAC address...'
		macchanger -r $interface

	else
		macchanger -m $1 $interface # change current device mac to input mac

	fi

	ifconfig $interface up
	dhclient $interface &> /dev/null # get a new ip

else

	echo ""
	echo "Incorrect number of arguments!"
	echo ""
	echo "Useage:"
	echo "$0 {mac address} {interface}"
	echo ""

fi
