#!/bin/bash

if [ $# -eq 3 ]
then
	interface=$2
        interfacemon="${interface}mon"

	echo ""
	ifconfig $interface down
	dhclient -r $interface &> /dev/null # release ip

	if [ "$1" = "reset" ]; then
		echo resetting
		macchanger -p $interface
	elif [ "$1" = "random" ]; then
		echo randomising
		macchanger -r $interface
	else
		macchanger -m $1 $interface # change current device mac to input mac
	fi

	ifconfig $interface up
	dhclient $interface &> /dev/null # get a new ip

	echo "New mac: $1"
	ifconfig $interface | grep inet
	echo ""
else
	echo ""
	echo "Incorrect number of arguments!"
	echo ""
	echo "Useage:"
	echo "$0 {mac address} {interface}"
	echo ""
fi
