#!/bin/bash

curdir=$(pwd)
logfile=installlog.txt

echo "Thanks for using houdini! Today's installation log file will be in $curdir/installlog.txt!"

echo "`date` - updating apt-get..." | tee -a $logfile
sudo apt-get update | tee -a $logfile

echo "`date` - installing dependencies..." | tee -a $logfile
sudo apt-get install -y aircrack-ng python3 git | tee -a $logfile

echo "`date` - cloning git repos..."
git clone https://github.com/oblique/create_ap | tee -a $logfile

echo "`date` - Finish." >> $logfile

echo "Done!"
