# Python 3
# Program to strip the macs from a csv generated by airodump-ng
# By ariakis

import sys, os

# Initialise variables
separator = "Station MAC"
doPrints = False
counter = 1

# Navigate to the correct directory and open files for read/write
inpFilename = os.path.abspath(os.path.dirname( __file__ )) + "/" + sys.argv[1]
inputFile = open(inpFilename,"r")

outFilename = os.path.abspath(os.path.dirname( __file__ )) + "/" + sys.argv[2]
outputFile = open(outFilename,"a")

# Main read loop

print()

for line in inputFile:
	if (line[:11] == separator): # Once we've reached the client macs
		doPrints = True
	elif (doPrints == True): # Start writing the macs to outputFile
		if not (line[76:92] == "(not associated)"): # if they're associated
			print(str(counter)+". "+str(line[:17]))
			if (counter > 1): # this ensures there's no blank lines
				outputFile.write("\n")
			outputFile.write(line[:17])
			counter = counter + 1

print("Found",counter-2,"MAC addresses!")

inputFile.close()
outputFile.close()

